name: validatePR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

concurrency:
  group: validatePR
  cancel-in-progress: true

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Validate Pull Request
        uses: jordandarlington/actions-workflow-test-core/actions/validate-pull-request@v0.1.13

  validate-branch:
    needs: validate-pull-request
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Check Branch Protection
        uses: jordandarlington/actions-workflow-test-core/actions/validate-branch@v0.1.13
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          org-name: jordandarlington
          repo-name: actions-workflow-test
          base-branch: ${{ github.event.pull_request.base.ref }}

  validate-build:
    needs: validate-branch
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo "$(date "+%F %H:%M:%S") | Install Dependencies | START"
          npm install
          echo "$(date "+%F %H:%M:%S") | Install Dependencies | END"

      - name: Compile TypeScript
        run: |
          echo "$(date "+%F %H:%M:%S") | Compile TypeScript | START"
          npm run build
          echo "$(date "+%F %H:%M:%S") | Compile TypeScript | END"

      - name: Run Tests
        run: |
          echo "$(date "+%F %H:%M:%S") | Run Tests | START"
          npm test
          echo "$(date "+%F %H:%M:%S") | Run Tests | END"