name: validatePR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

concurrency:
  group: validatePR
  cancel-in-progress: true

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Pull Request Draft Status
        run: |
          echo "$(date "+%F %H:%M:%S") | Check Pull Request Draft Status | START"
          if [ ${{ github.event.pull_request.draft }} == true ]; then
            echo "$(date "+%F %H:%M:%S") | Check Pull Request Draft Status | FAILURE"
            exit 1;
          fi
          echo "$(date "+%F %H:%M:%S") | Check Pull Request Draft Status | END"

      - name: Check Pull Request Description
        run: |
          echo "$(date "+%F %H:%M:%S") | Check Pull Request Description | START"
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "$(date "+%F %H:%M:%S") | Check Pull Request Description | FAILURE"
            exit 1;
          fi
          echo "$(date "+%F %H:%M:%S") | Check Pull Request Description | END"

  validate-branch:
    needs: validate-pull-request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Branch Protection
        uses: jordandarlington/actions-workflow-test-core/actions/validate-branch@initial-test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          org-name: jordandarlington
          repo-name: actions-workflow-test
          base-branch: ${{ github.event.pull_request.base.ref }}

  validate-build:
    needs: validate-branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          echo "$(date "+%F %H:%M:%S") | Install Dependencies | START"
          npm install
          echo "$(date "+%F %H:%M:%S") | Install Dependencies | END"

      - name: Compile TypeScript
        run: |
          echo "$(date "+%F %H:%M:%S") | Compile TypeScript | START"
          npm run build
          echo "$(date "+%F %H:%M:%S") | Compile TypeScript | END"

      - name: Run Tests
        run: |
          echo "$(date "+%F %H:%M:%S") | Run Tests | START"
          npm test
          echo "$(date "+%F %H:%M:%S") | Run Tests | END"